/*
 * Stub for class com.danielkim.soundrecorder.DoPrint
 * Generated by Sapphire Compiler (sc).
 */
package com.danielkim.soundrecorder.stubs;


public final class DoPrint_Stub extends com.danielkim.soundrecorder.DoPrint implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public DoPrint_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of PrintMsg()
    public void PrintMsg() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.PrintMsg();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.danielkim.soundrecorder.DoPrint.PrintMsg()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
